name: 'Direct merge'

description: 'GitHub action which merges one branch into another'

branding:
  color: 'green'
  icon: 'git-merge'

inputs:
  owner: # owner of the repo
    description: 'Owner of the repo. Defaults to current repository owner'
    required: false

  repo: # name of the repo
    description: 'Name of the repo. Defaults to current repository'
    required: false

  source-branch: # name of source branch
    description: 'Name of the source branch (from)'
    required: true

  target-branch: # name of target branch
    description: 'Name of the target branch (to)'
    required: true

  commit-message: # commit message
    description: 'Message to use for the commit. If empty then a default message will be used ("Automatic merge of <source-branch> -> <target-branch>")'
    required: false

  GITHUB_TOKEN:
    description: 'Repository access token. For example: secrets.GITHUB_TOKEN'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
