name: Master push

on:
  push:
    branches: [master]

jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Merge master -> develop
    steps:
      - uses: actions/checkout@v2
      - name: Merge action
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          owner: tukasz
          repo: direct-merge-action
          source-branch: master
          target-branch: develop
